name: ronda_app
description: "Ronda marocaine - jeu de cartes multijoueur en ligne."
publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^3.0.0
  provider: ^6.1.2
  shared_preferences: ^2.5.5
  google_mobile_ads: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/cards/
    - assets/ui/
  fonts:
    - family: Lilita
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#1A0F08"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
